// Ticora Store — Supabase config
const SUPABASE_URL = 'https://wnfsukalmaycwdihumlb.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduZnN1a2FsbWF5Y3dkaWh1bWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0Mjc3MDUsImV4cCI6MjA4NjAwMzcwNX0._pngqv59gq-hlLDy2nWEtCzcdlUmZT94Q2lXRhfXaRU';
